import { createApp } from "vue";
import "./index.css";
import App from "./App.vue";
import { OhVueIcon, addIcons } from "oh-vue-icons";
import {
  MdNotstartedSharp,
  RiAppsLine,
  IoLogoGooglePlaystore,
  MdNotealtOutlined,
  MdMedicalservicesOutlined,
  HiChatAlt,
  MdBookmarks,
  MdMenubookOutlined,
  SiChatbot,
  BiFacebook,
  CoInstagram,
  BiYoutube,
  HiPhone,
  HiMail,
  HiMap,
  AiAcclaim,
  ViFileTypeHtml,
  ViFileTypeCss,
  SiJavascript,
  ViFileTypeVue,
  ViFileTypeVite,
  ViFileTypeTailwind,
  ViFileTypePython,
  ViFileTypeDartlang,
  ViFileTypeFlutter,
  CoFlask,
  ViFileTypeYarn,
  ViFileTypeNode,
  ViFileTypeMysql,
  SiScikitlearn,
  ViFileTypeNpm,
} from "oh-vue-icons/icons";

addIcons(
  MdNotstartedSharp,
  RiAppsLine,
  IoLogoGooglePlaystore,
  MdNotealtOutlined,
  MdMedicalservicesOutlined,
  HiChatAlt,
  MdBookmarks,
  MdMenubookOutlined,
  SiChatbot,
  BiFacebook,
  CoInstagram,
  BiYoutube,
  HiPhone,
  HiMail,
  HiMap,
  AiAcclaim,
  ViFileTypeHtml,
  ViFileTypeCss,
  SiJavascript,
  ViFileTypeVue,
  ViFileTypeVite,
  ViFileTypeTailwind,
  ViFileTypePython,
  ViFileTypeDartlang,
  ViFileTypeFlutter,
  CoFlask,
  ViFileTypeYarn,
  ViFileTypeNode,
  ViFileTypeMysql,
  SiScikitlearn,
  ViFileTypeNpm,
);

createApp(App).component("v-icon", OhVueIcon).mount("#app");
